# -*- coding: utf-8 -*-
"""notes app manager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-p2pa50dzyPVYH3HiGkq5ysHoqOlxoYu
"""

pip install streamlit pandas openpyxl

import streamlit as st
import pandas as pd
from datetime import datetime
import os

# ---------- CONFIG ----------
st.set_page_config(page_title="AI Notes Manager", layout="wide")

# ---------- STYLE ----------
st.markdown("""
    <style>
    .main {background-color: #0E1117; color: white;}
    .stButton>button {
        background-color: #4CAF50;
        color: white;
        border-radius: 10px;
        padding: 10px;
    }
    </style>
""", unsafe_allow_html=True)

# ---------- DATA ----------
FILE = "notes_data.xlsx"

if os.path.exists(FILE):
    df = pd.read_excel(FILE)
else:
    df = pd.DataFrame(columns=["ID", "Title", "Category", "Content", "Timestamp"])

# ---------- HEADER ----------
st.title("🧠 AI Notes Manager")
st.caption("Organize. Search. Enhance with AI 🚀")

# ---------- SIDEBAR ----------
menu = st.sidebar.radio("📌 Navigation", [
    "🏠 Dashboard",
    "➕ Add Note",
    "📋 View Notes",
    "🔍 Search",
    "🗑️ Delete",
    "🤖 AI Tools"
])

# ---------- DASHBOARD ----------
if menu == "🏠 Dashboard":
    st.subheader("📊 Overview")

    col1, col2, col3 = st.columns(3)

    col1.metric("Total Notes", len(df))
    col2.metric("Work Notes", len(df[df["Category"] == "Work"]))
    col3.metric("Ideas", len(df[df["Category"] == "Ideas"]))

    st.divider()

    st.subheader("📁 Recent Notes")
    st.dataframe(df.tail(5), use_container_width=True)

# ---------- ADD ----------
elif menu == "➕ Add Note":
    st.subheader("Add New Note")

    col1, col2 = st.columns(2)

    with col1:
        note_id = st.text_input("Note ID")
        title = st.text_input("Title")

    with col2:
        category = st.selectbox("Category", ["Work", "Personal", "Ideas"])

    content = st.text_area("Content")

    if st.button("🚀 Add Note"):
        if note_id in df["ID"].values:
            st.error("ID already exists!")
        elif content == "":
            st.error("Content cannot be empty!")
        else:
            new = pd.DataFrame({
                "ID":[note_id],
                "Title":[title],
                "Category":[category],
                "Content":[content],
                "Timestamp":[datetime.now()]
            })
            df = pd.concat([df, new], ignore_index=True)
            df.to_excel(FILE, index=False)
            st.success("✅ Note added!")

# ---------- VIEW ----------
elif menu == "📋 View Notes":
    st.subheader("All Notes")

    if df.empty:
        st.warning("No notes yet")
    else:
        st.dataframe(df, use_container_width=True)

# ---------- SEARCH ----------
elif menu == "🔍 Search":
    st.subheader("Search Notes")

    keyword = st.text_input("Enter keyword")

    if keyword:
        result = df[df["Content"].str.contains(keyword, case=False, na=False)]

        if result.empty:
            st.warning("No results found")
        else:
            st.dataframe(result, use_container_width=True)

# ---------- DELETE ----------
elif menu == "🗑️ Delete":
    st.subheader("Delete Note")

    note_id = st.text_input("Enter Note ID")

    if st.button("Delete"):
        if note_id in df["ID"].values:
            df = df[df["ID"] != note_id]
            df.to_excel(FILE, index=False)
            st.success("Deleted successfully")
        else:
            st.error("Note not found")

# ---------- AI TOOLS ----------
elif menu == "🤖 AI Tools":
    st.subheader("AI Features (Coming Next 🚀)")

    st.info("👉 Add OpenAI/Groq API to enable:\n- Summarize\n- Rewrite\n- Idea Generator")

    note_text = st.text_area("Paste your note here")

    if st.button("✨ Generate AI Output"):
        st.warning("AI not connected yet 😅")

